# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'The Little Bird' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for The Little Bird

  target 'The Little BirdTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'The Little BirdUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

pod 'Fabric'
pod 'TwitterKit'
pod 'STTwitter'